import React from 'react';

const Dogs = () => {
    return (
        <div>
            <h1>Dogs</h1>

            <div className="dogPhoto">
                {/* <img src="https://images.dog.ceo/breeds/chihuahua/n02085620_11258.jpg" alt="error" /> */}
            </div>

            <div className="dogsFact">
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugiat praesentium dolorem amet assumenda dicta magni veritatis, esse nam suscipit recusandae.</p>
            </div>
        </div>
    );
};

export default Dogs;